# docker-compose.yml
version: '3.9'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
